### ISSUE TITLE
Bug in Makefile

### ISSUE THREAD

**Issue by mpasserini** [guedes/ldap_fdw#13]
Hi,

I think there's a bug in the Makefile. I'm trying to install ldap_fdw-0.1.1 on CentOS release 6.4 (Final), with:
make-3.81-20.el6.x86_64
postgresql93-devel-9.3.1-1PGDG.rhel6.x86_64
gcc-4.4.7-4.el6.x86_64
openldap-devel-2.4.23-32.el6_4.1.x86_64
postgresql93-9.3.1-1PGDG.rhel6.x86_64

If I type make it compiles, but then I say make install it says:

[root@localhost ldap_fdw-0.1.1]# make install
/bin/mkdir -p '/usr/pgsql-9.3/lib'
/bin/mkdir -p '/usr/pgsql-9.3/share/extension'
/bin/mkdir -p '/usr/pgsql-9.3/share/extension'
/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/usr/bin/install -c -m 755  ldap_fdw.so '/usr/pgsql-9.3/lib/ldap_fdw.so'
/usr/bin/install -c -m 644 ./ldap_fdw.control '/usr/pgsql-9.3/share/extension/'
/usr/bin/install -c -m 644 ./sql/ldap_fdw--0.1.1.sql ./sql/ldap_fdw--0.1.1.sql  '/usr/pgsql-9.3/share/extension/'
/usr/bin/install: will not overwrite just-created `/usr/pgsql-9.3/share/extension/ldap_fdw--0.1.1.sql' with `./sql/ldap_fdw--0.1.1.sql'

To fix the problem I deleted the following file after running make: sql/ldap_fdw--0.1.1.sql .
Now it seems to install it correctly. But I will do more tests.

**Comment by xiu1** [comment]
```diff
diff --git a/Makefile b/Makefile
index 24effdc..8b2d8f9 100644
--- a/Makefile
+++ b/Makefile
@@ -20,7 +20,7 @@ all: sql/$(EXTENSION)--$(EXTVERSION).sql
 sql/$(EXTENSION)--$(EXTVERSION).sql: sql/$(EXTENSION).sql
        cp $< $@
 
-DATA = $(wildcard sql/*--*.sql) sql/$(EXTENSION)--$(EXTVERSION).sql
+DATA = sql/$(EXTENSION)--$(EXTVERSION).sql
 EXTRA_CLEAN = sql/$(EXTENSION)--$(EXTVERSION).sql
 endif
```

**Comment by guedes** [comment]
It seems to fix that. Thanks!
